<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0</TargetFramework>
    <RootNamespace>NewTso2Pmx.App</RootNamespace>
    <AssemblyName>NewTso2Pmx.App</AssemblyName>
    <AvaloniaUseCompiledBindingsByDefault>false</AvaloniaUseCompiledBindingsByDefault>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\NewTso2Pmx.Compatibility\NewTso2Pmx.Compatibility.csproj" />
    <ProjectReference Include="..\NewTso2Pmx.Core\NewTso2Pmx.Core.csproj" />
    <ProjectReference Include="..\NewTso2Pmx.Renderer\NewTso2Pmx.Renderer.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia" />
    <PackageReference Include="Avalonia.Desktop" />
    <PackageReference Include="Avalonia.Themes.Fluent" />
    <PackageReference Include="SixLabors.ImageSharp" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="PhysObTemplate\**\*.cs" />
    <Compile Remove="Proportion\**\*.cs" />
    <None Include="PhysObTemplate\**\*.cs;Proportion\**\*.cs" CopyToOutputDirectory="PreserveNewest" />
    <None Update="CorrespondTable\**\*;PhysObTemplate\**\*;Proportion\**\*;表情\**\*;TPOConfig.xml" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

</Project>
