<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <RootNamespace>NewTso2Pmx.Renderer</RootNamespace>
    <AssemblyName>NewTso2Pmx.Renderer</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\NewTso2Pmx.Compatibility\NewTso2Pmx.Compatibility.csproj" />
    <ProjectReference Include="..\NewTso2Pmx.Core\NewTso2Pmx.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia" />
    <PackageReference Include="Silk.NET.OpenGL" />
  </ItemGroup>

</Project>
