<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <RootNamespace>NewTso2Pmx.Core</RootNamespace>
    <AssemblyName>NewTso2Pmx.Core</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\NewTso2Pmx.Compatibility\NewTso2Pmx.Compatibility.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp" />
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp.Scripting" />
    <PackageReference Include="SharpZipLib" />
    <PackageReference Include="SixLabors.ImageSharp" />
    <PackageReference Include="System.Text.Encoding.CodePages" />
  </ItemGroup>

</Project>
